import '../models/video_model.dart';

class CropVideoService {
  CropVideoService._();

  static final List<AgriVideoModel> allCropVideos = [
    // 1. COTTON (పత్తి)
    const AgriVideoModel(
      id: 'v_cotton_pink_bollworm',
      cropId: 'c_cotton',
      titleTe: 'పత్తిలో గులాబీ రంగు పురుగు నివారణ సమగ్ర IPM పద్ధతి',
      titleEn: 'Pink Bollworm Scientific IPM Control in Cotton',
      titleHi: 'कपास में गुलाबी सुंडी का वैज्ञानिक नियंत्रण',
      category: 'Pest Control',
      instructorName: 'Dr. సుమిత్ర దేవి (Dr. Sumitra Devi)',
      instructorTitle: 'Senior Entomologist, ICAR-CRIDA',
      duration: '07:45',
      viewsCount: '64.2K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1595856754020-008bc592d37c?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=cotton+pink+bollworm+management+telugu+icar',
      sourceOrg: 'ICAR - Central Institute for Cotton Research',
      videoDescriptionTe: 'పత్తి కాయల్లోకి చొరబడే గులాబీ రంగు పురుగును లింగాకర్షక బుట్టలు మరియు సూచించిన రసాయనాలతో మొదటి దశలోనే ఎలా అరికట్టవచ్చో ప్రత్యక్ష క్షేత్ర ప్రదర్శన.',
      videoDescriptionEn: 'Field demonstration of pheromone traps and targeted chemical rotation against pink bollworm in cotton.',
      videoDescriptionHi: 'कपास में फेरोमोन ट्रैप एवं कीटनाशक चक्र द्वारा गुलाबी सुंडी का सफल नियंत्रण।',
      keyTakeawaysTe: [
        'ఎకరాకు 8 లింగాకర్షక బుట్టలను పంట కంటే 1 అడుగు ఎత్తులో అమర్చండి.',
        'వరుసగా 3 రోజులు బుట్టకు 8 రెక్కల పురుగులు పడితే వెంటనే పిచికారీ చేయాలి.',
        'ప్రొఫెనోఫాస్ 2 మి.లీ లేదా ఎమామెక్టిన్ బెంజోయేట్ 0.5 గ్రా. లీటరు నీటికి కలపండి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:15', titleTe: 'గులాబీ పురుగు జీవిత చక్రం', titleEn: 'Pest Life Cycle'),
        VideoChapter(timestamp: '02:10', titleTe: 'ట్రాప్స్ ఏర్పాటు విధానం', titleEn: 'Trap Installation'),
        VideoChapter(timestamp: '04:30', titleTe: 'సమగ్ర రసాయన పిచికారీ', titleEn: 'Chemical Sprays'),
        VideoChapter(timestamp: '06:20', titleTe: 'కోత తర్వాత తీసుకోవాల్సిన జాగ్రత్తలు', titleEn: 'Post-Harvest Cleanup'),
      ],
    ),
    const AgriVideoModel(
      id: 'v_cotton_hdps',
      cropId: 'c_cotton',
      titleTe: 'పత్తిలో అధిక సాంద్రత సాగు పద్ధతి (HDPS) & ఎరువుల ప్రణాళిక',
      titleEn: 'High Density Planting System (HDPS) in Cotton',
      titleHi: 'कपास में सघन रोपण तकनीक (HDPS) एवं खाद प्रबंधन',
      category: 'Cultivation',
      instructorName: 'Dr. రవీందర్ రెడ్డి (Dr. Ravinder Reddy)',
      instructorTitle: 'Principal Agronomist, PJTSAU',
      duration: '08:20',
      viewsCount: '51.8K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=cotton+hdps+cultivation+pjtsau+telugu',
      sourceOrg: 'PJTSAU Agricultural University',
      videoDescriptionTe: 'ఎకరానికి 25,000 మొక్కలతో పత్తి సాగు చేసి ఎకరానికి 15-18 క్వింటాళ్ల దిగుబడి సాధించే ఆధునిక HDPS విధానంపై శాస్త్రవేత్తల ప్రదర్శన.',
      videoDescriptionEn: 'HDPS method in cotton with 25,000 plants per acre yielding 15-18 quintals with lower labour costs.',
      keyTakeawaysTe: [
        'వరుసల మధ్య 90 సెం.మీ, మొక్కల మధ్య 15-20 సెం.మీ ఎడం పాటించాలి.',
        'మొక్క ఎత్తు 4-5 అడుగులు దాటకుండా సైకోసిల్ లేదా చమత్కార్ స్ప్రే చేయాలి.',
        'మొత్తం కాయలు ఒకేసారి పక్వానికి వచ్చి ఒకే లేదా రెండు కోతల్లో పూర్తవుతాయి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'HDPS ప్రాముఖ్యత', titleEn: 'Why HDPS?'),
        VideoChapter(timestamp: '02:40', titleTe: 'విత్తే దూరం & రకాలు', titleEn: 'Spacing & Varieties'),
        VideoChapter(timestamp: '05:15', titleTe: 'ఎత్తు నియంత్రణ మందులు', titleEn: 'Growth Regulators'),
        VideoChapter(timestamp: '07:00', titleTe: 'దిగుబడి లెక్కింపు', titleEn: 'Yield Calculations'),
      ],
    ),

    // 2. PADDY (వరి)
    const AgriVideoModel(
      id: 'v_paddy_sri',
      cropId: 'c_paddy',
      titleTe: 'వరిలో శ్రీ (SRI) సాగు విధానం & నీటి ఆదా టెక్నిక్స్',
      titleEn: 'System of Rice Intensification (SRI) & AWD Technology',
      titleHi: 'धान में श्री विधि एवं जल बचत तकनीक',
      category: 'Cultivation',
      instructorName: 'Dr. కృష్ణారావు (Dr. Krishna Rao)',
      instructorTitle: 'Senior Rice Breeder, ICAR-IIRR Hyderabad',
      duration: '09:10',
      viewsCount: '89.4K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1536657464919-892534f60d6e?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=paddy+sri+method+telugu+farming',
      sourceOrg: 'ICAR - Indian Institute of Rice Research',
      videoDescriptionTe: 'ఎకరానికి కేవలం 2 కిలోల విత్తనంతో, 10-12 రోజుల లేత నారు నాటి 40% నీటిని ఆదా చేస్తూ ఎకరాకు 35 క్వింటాళ్ల దిగుబడి సాధించే పద్ధతి.',
      videoDescriptionEn: 'SRI method in paddy cultivation saving 40% water and 80% seed with maximum tillering and aeration.',
      keyTakeawaysTe: [
        '10-12 రోజుల లేత నారును 25x25 సెం.మీ చతురస్రాకారంలో నాటాలి.',
        'కొనోవీడర్‌తో 10 రోజుల వ్యవధిలో 4 సార్లు కలుపు తీస్తూ భూమిని గుల్లపరచాలి.',
        'నిరంతరం నీరు నిలపకుండా తడి ఆరిన తర్వాత మాత్రమే నీరు పెట్టాలి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'శ్రీ పద్ధతి ప్రాథమిక సూత్రాలు', titleEn: 'Principles of SRI'),
        VideoChapter(timestamp: '02:30', titleTe: 'నారుమడి యాజమాన్యం', titleEn: 'Nursery Management'),
        VideoChapter(timestamp: '05:00', titleTe: 'కొనోవీడర్ నడిపే విధానం', titleEn: 'Cono-Weeder Operation'),
        VideoChapter(timestamp: '07:30', titleTe: 'నీటి తడుల షెడ్యూల్', titleEn: 'AWD Irrigation Schedule'),
      ],
    ),
    const AgriVideoModel(
      id: 'v_paddy_blast',
      cropId: 'c_paddy',
      titleTe: 'వరిలో అగ్గితెగులు (Blast) & కాండం తొలుచు పురుగు నివారణ',
      titleEn: 'Paddy Blast Disease & Stem Borer Management',
      titleHi: 'धान में ब्लास्ट रोग एवं तना छेदक रोकथाम',
      category: 'Pest Control',
      instructorName: 'Dr. లక్ష్మీ ప్రసన్న (Dr. Lakshmi Prasanna)',
      instructorTitle: 'Plant Pathologist, PJTSAU',
      duration: '06:55',
      viewsCount: '47.1K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=paddy+blast+disease+stem+borer+telugu',
      sourceOrg: 'PJTSAU Agricultural University',
      videoDescriptionTe: 'వరి ఆకులపై కంటి ఆకారపు మచ్చలు కనిపించినప్పుడు ట్రైసైక్లాజోల్ మరియు కాండం తొలుచు పురుగుకు కార్టాప్ హైడ్రోక్లోరైడ్ వాడే ఖచ్చితమైన మోతాదులు.',
      videoDescriptionEn: 'Identification and chemical control of Rice Blast and Yellow Stem Borer to prevent white ears.',
      keyTakeawaysTe: [
        'అగ్గితెగులు నివారణకు లీటరు నీటికి 0.6 గ్రా. ట్రైసైక్లాజోల్ పిచికారీ చేయాలి.',
        'మబ్బులు ఉన్న వాతావరణంలో యూరియా వాడకాన్ని తగ్గించండి.',
        'కాండం తొలుచు పురుగుకు కార్టాప్ హైడ్రోక్లోరైడ్ 4G గుళికలు ఎకరాకు 8 కిలోలు చల్లండి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:15', titleTe: 'అగ్గితెగులు లక్షణాలు', titleEn: 'Symptoms'),
        VideoChapter(timestamp: '02:20', titleTe: 'సమగ్ర నివారణ చర్యలు', titleEn: 'Chemical Sprays'),
        VideoChapter(timestamp: '04:40', titleTe: 'కాండం తొలుచు పురుగు గుర్తింపు', titleEn: 'Stem Borer Traps'),
      ],
    ),

    // 3. CHILLI (మిరప)
    const AgriVideoModel(
      id: 'v_chilli_thrips',
      cropId: 'c_chilli',
      titleTe: 'మిరపలో నల్ల తామర పురుగు (Invasive Thrips) నివారణ వ్యూహం',
      titleEn: 'Management of Invasive Black Thrips in Chilli',
      titleHi: 'मिर्च में इनवेसिव ब्लैक थ्रिप्स का नियंत्रण',
      category: 'Pest Control',
      instructorName: 'Dr. వెంకటేశ్వర్లు (Dr. Venkateshwarlu)',
      instructorTitle: 'Principal Scientist, IIHR Horticulture',
      duration: '08:35',
      viewsCount: '78.9K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=chilli+black+thrips+control+telugu',
      sourceOrg: 'ICAR - Indian Institute of Horticultural Research',
      videoDescriptionTe: 'మిరప పూత రాలడం మరియు ఆకులు గిడసబారే నల్ల తామర పురుగును అరికట్టే బ్లూ స్టికి ట్రాప్స్ మరియు నూతన రసాయనాల సమగ్ర గైడ్.',
      videoDescriptionEn: 'Complete scientific guide to blue sticky traps, bio-pesticides and chemical rotation against Thrips parvispinus.',
      keyTakeawaysTe: [
        'ఎకరాకు 30 నీలం రంగు జిగురు అట్టలను పైరు ఎత్తులో అమర్చాలి.',
        'లీటరు నీటికి స్పైనిటోరమ్ 1 మి.లీ లేదా డయాఫెంథియురాన్ 1.25 గ్రా. స్ప్రే చేయండి.',
        'రసాయనాలకు తోడుగా వేప నూనె (10,000 ppm) 1 మి.లీ కలిపి వాడాలి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'నల్ల తామర పురుగు దాడి లక్షణాలు', titleEn: 'Identification'),
        VideoChapter(timestamp: '02:30', titleTe: 'నీలం రంగు జిగురు అట్టల ఏర్పాటు', titleEn: 'Blue Sticky Traps'),
        VideoChapter(timestamp: '05:10', titleTe: 'రసాయనాల మార్పిడి పిచికారీ', titleEn: 'Pesticide Rotation'),
      ],
    ),
    const AgriVideoModel(
      id: 'v_chilli_drip_mulch',
      cropId: 'c_chilli',
      titleTe: 'మిరపలో సిల్వర్ బ్లాక్ మల్చింగ్ & డ్రిప్ ఫెర్టిగేషన్ విధానం',
      titleEn: 'Silver-Black Mulch & Drip Fertigation in Chilli',
      titleHi: 'मिर्च में मल्चिंग एवं ड्रिप फर्टिगेशन तकनीक',
      category: 'Cultivation',
      instructorName: 'శ్రీ సుధాకర్ రావు (M. Sudhakar Rao)',
      instructorTitle: 'Horticulture Specialist, Telangana Dept',
      duration: '07:15',
      viewsCount: '53.0K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=chilli+mulching+sheet+drip+telugu',
      sourceOrg: 'Spices Board & Horticulture Extension',
      videoDescriptionTe: 'ఎకరానికి 30 మైక్రాన్ల మల్చింగ్ షీట్ వేసి 19:19:19 మరియు 13:0:45 ఎరువులను డ్రిప్ ద్వారా అందిస్తూ ఎకరానికి 35 క్వింటాళ్ల ఎండుమిర్చి సాధించే విధానం.',
      videoDescriptionEn: 'High-tech chilli cultivation using plastic mulch sheet and soluble NPK fertigation schedule.',
      keyTakeawaysTe: [
        'మల్చింగ్ వల్ల 90% కలుపు నివారణ మరియు 40% తేమ ఆదా అవుతుంది.',
        'పూత దశలో బోరాన్ మరియు కాల్షియం నైట్రేట్ పిచికారీ చేయాలి.',
        'తేలికపాటి గరప నేలల్లో బోదెల ఎత్తు 1 అడుగు ఉండేలా చూడండి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:15', titleTe: 'బోదెలు వేయడం & మల్చింగ్', titleEn: 'Bed Prep & Mulching'),
        VideoChapter(timestamp: '02:40', titleTe: 'నారు నాటే పద్ధతి', titleEn: 'Transplanting'),
        VideoChapter(timestamp: '04:50', titleTe: 'వారపు ఫెర్టిగేషన్ చార్ట్', titleEn: 'Fertigation Schedule'),
      ],
    ),

    // 4. MAIZE (మొక్కజొన్న)
    const AgriVideoModel(
      id: 'v_maize_faw',
      cropId: 'c_maize',
      titleTe: 'మొక్కజొన్నలో కత్తెర పురుగు (Fall Armyworm) శాస్త్రీయ నిర్మూలన',
      titleEn: 'Scientific Fall Armyworm (FAW) IPM in Maize',
      titleHi: 'मक्का में फॉल आर्मीवर्म का वैज्ञानिक नियंत्रण',
      category: 'Pest Control',
      instructorName: 'Dr. రాజేష్ కుమార్ (Dr. Rajesh Kumar)',
      instructorTitle: 'Senior Maize Scientist, ICAR-IIMR',
      duration: '06:40',
      viewsCount: '49.8K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=maize+fall+armyworm+control+telugu',
      sourceOrg: 'ICAR - Indian Institute of Maize Research',
      videoDescriptionTe: 'విత్తిన 15 రోజుల నుండి మొక్కజొన్న సుడులలో చేరే కత్తెర పురుగును వేప ద్రావణం మరియు కోరాజెన్ పిచికారీతో సమర్థవంతంగా అణచివేసే పద్ధతి.',
      videoDescriptionEn: 'Early detection and whorl application methods against Fall Armyworm to save maize cobs.',
      keyTakeawaysTe: [
        'విత్తిన 10వ రోజునే మొలకల ఆకులపై పిండి వంటి రంధ్రాలు గమనించాలి.',
        'మొక్క సుడిలో నేరుగా పడేలా క్లోరంత్రానిలిప్రోల్ 0.4 మి.లీ స్ప్రే చేయండి.',
        'బెల్లం, తవుడు మరియు థయోడికార్బ్‌తో విషపు ఎర ఉండలు వేయడం వల్ల పెద్ద పురుగులు చనిపోతాయి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:15', titleTe: 'కత్తెర పురుగు ఉనికి గుర్తించడం', titleEn: 'Scouting'),
        VideoChapter(timestamp: '02:10', titleTe: 'సుడులలో స్ప్రే విధానం', titleEn: 'Whorl Application'),
        VideoChapter(timestamp: '04:30', titleTe: 'విషపు ఎర తయారీ పద్ధతి', titleEn: 'Poison Baiting'),
      ],
    ),
    const AgriVideoModel(
      id: 'v_maize_cob',
      cropId: 'c_maize',
      titleTe: 'మొక్కజొన్నలో కంకి సైజు & గింజ బరువు పెంచే ఎరువుల ప్రణాళిక',
      titleEn: 'Maize Cob Development & Micronutrient Schedule',
      titleHi: 'मक्का भुट्टे का आकार एवं दाना भराव प्रबंधन',
      category: 'Fertilizer',
      instructorName: 'Dr. రవీందర్ రెడ్డి (Dr. Ravinder Reddy)',
      instructorTitle: 'Principal Agronomist, PJTSAU',
      duration: '07:20',
      viewsCount: '38.4K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=maize+fertilizer+schedule+telugu',
      sourceOrg: 'PJTSAU Agri Extension',
      videoDescriptionTe: 'మోకాలి ఎత్తు దశ, పూత దశ మరియు గింజ పాలు పోసుకునే దశల్లో పొటాష్, జింక్ మరియు నత్రజని వేయడం ద్వారా 35+ క్వింటాళ్లు పొందే టెక్నిక్.',
      videoDescriptionEn: 'Nutrient management for uniform cob filling and heavy test weight in hybrid maize.',
      keyTakeawaysTe: [
        'ఎకరాకు 20 కిలోల జింక్ సల్ఫేట్ చివరి దుక్కిలో తప్పనిసరిగా వేయాలి.',
        'మోకాలి ఎత్తు దశలో 35 కిలోల యూరియా, కంకి దశలో 25 కిలోల యూరియా వేయండి.',
        'గింజ కట్టే దశలో 0:0:50 లేదా 13:0:45 పిచికారీ చేస్తే గింజలు బరువుగా మారతాయి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'పోషకాల ప్రాముఖ్యత', titleEn: 'Nutrient Need'),
        VideoChapter(timestamp: '02:15', titleTe: 'మోకాలి ఎత్తు దశ ఎరువులు', titleEn: 'Knee-high Stage'),
        VideoChapter(timestamp: '05:00', titleTe: 'కంకి పాలు పోసుకునే దశ స్ప్రే', titleEn: 'Grain Filling Spray'),
      ],
    ),

    // 5. RED GRAM (కందులు)
    const AgriVideoModel(
      id: 'v_redgram_nipping',
      cropId: 'c_redgram',
      titleTe: 'కందులలో కొమ్మలు రెట్టింపు చేసే చిగుళ్ళు తుంచే విధానం (Nipping)',
      titleEn: 'Nipping Technique in Redgram for Double Branching',
      titleHi: 'अरहर में अधिक शाखाओं हेतु शीर्ष कटाई (निपिंग)',
      category: 'Cultivation',
      instructorName: 'Dr. శ్రీనివాస్ (Dr. Srinivas)',
      instructorTitle: 'Pulse Breeder, ICAR-IIPR',
      duration: '06:15',
      viewsCount: '42.6K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=redgram+nipping+telugu+kandulu',
      sourceOrg: 'ICAR - Indian Institute of Pulses Research',
      videoDescriptionTe: 'విత్తిన 45-50 రోజులకు మొక్క పైభాగాన్ని 2-3 అంగుళాలు కత్తిరించడం వల్ల నిలువు ఎదుగుదల ఆగి, పక్క కొమ్మలు 30 వరకు వచ్చి దిగుబడి రెట్టింపు అవుతుంది.',
      videoDescriptionEn: 'Scientific nipping demo in pigeonpea to trigger lateral branching and double the pod clusters per plant.',
      keyTakeawaysTe: [
        'మొక్క ఎత్తు 1.5 - 2 అడుగులు ఉన్నప్పుడు మాత్రమే చిగుళ్ళు తుంచాలి.',
        'చిగుళ్ళు తుంచిన 5 రోజులలోపు యూరియా లేదా 19:19:19 స్ప్రే చేయండి.',
        'దీని ద్వారా చెట్టు గొడుగులాగా విస్తరించి ఎకరానికి 10-12 క్వింటాళ్లు వస్తుంది.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:15', titleTe: 'నిప్పింగ్ సైన్స్ వివరణ', titleEn: 'Science of Nipping'),
        VideoChapter(timestamp: '02:00', titleTe: 'సరైన సమయం & కత్తిరించే పద్ధతి', titleEn: 'Right Timing & Cut'),
        VideoChapter(timestamp: '04:30', titleTe: 'నిప్పింగ్ తర్వాత పోషకాలు', titleEn: 'Post-Nipping Spray'),
      ],
    ),

    // 6. GROUNDNUT (వేరుశనగ)
    const AgriVideoModel(
      id: 'v_groundnut_gypsum',
      cropId: 'c_groundnut',
      titleTe: 'వేరుశనగలో జిప్సం ఎప్పుడు వేయాలి? కాయ సైజు పెంచే విధానం',
      titleEn: 'Gypsum Application & Peg Formation in Groundnut',
      titleHi: 'मूंगफली में जिप्सम का सही समय एवं उपयोग',
      category: 'Fertilizer',
      instructorName: 'Dr. అనిల్ కుమార్ (Dr. Anil Kumar)',
      instructorTitle: 'Senior Agronomist, ICAR-DGR',
      duration: '07:05',
      viewsCount: '39.8K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1599818816947-66c303102379?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=groundnut+gypsum+application+telugu',
      sourceOrg: 'ICAR - Directorate of Groundnut Research',
      videoDescriptionTe: 'వేరుశనగలో ఊడలు దిగే 40-45 రోజుల దశలో ఎకరాకు 200 కిలోల జిప్సం వేయడం ద్వారా బోలు కాయలు రాకుండా బరువైన గింజలు పొందడం ఎలా.',
      videoDescriptionEn: 'Critical role of Calcium and Sulphur from Gypsum for robust peg development and kernel filling in peanut.',
      keyTakeawaysTe: [
        'విత్తిన 40-45 రోజులప్పుడు మొదటి కలుపు తీసిన వెంటనే జిప్సం వేయాలి.',
        'జిప్సం వేసిన తర్వాత మొక్క మొదళ్ల వద్ద మట్టిని ఎగదోయాలి.',
        'జిప్సం వేయడం వల్ల కాయల్లో నూనె శాతం మరియు గింజ బరువు 25% పెరుగుతుంది.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:15', titleTe: 'కాల్షియం లోపం & బోలు కాయలు', titleEn: 'Calcium Deficiency'),
        VideoChapter(timestamp: '02:20', titleTe: 'జిప్సం వేసే పద్ధతి & సమయం', titleEn: 'Gypsum Dosage'),
        VideoChapter(timestamp: '04:50', titleTe: 'మొదళ్లకు మట్టి ఎగదోయడం', titleEn: 'Earthing Up'),
      ],
    ),

    // 7. TOMATO (టమాట)
    const AgriVideoModel(
      id: 'v_tomato_trellising',
      cropId: 'c_tomato',
      titleTe: 'టమాటాల్లో తాళ్ల పద్ధతి (Trellising) - ఎకరానికి 40 టన్నుల దిగుబడి',
      titleEn: 'Tomato Staking & Trellising System for Commercial Yield',
      titleHi: 'टमाटर में तार-बांस बंधाई विधि (ट्रेली तकनीक)',
      category: 'Cultivation',
      instructorName: 'Dr. వెంకటేశ్వర్లు (Dr. Venkateshwarlu)',
      instructorTitle: 'Horticulturist, IIHR Bangalore',
      duration: '08:40',
      viewsCount: '67.3K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=tomato+trellising+method+telugu',
      sourceOrg: 'ICAR - Indian Institute of Horticultural Research',
      videoDescriptionTe: 'టమాట మొక్కలు నేలపై పాకకుండా కర్రలు, జీఐ వైర్లతో పైకి కట్టడం వల్ల కాయలు కుళ్ళిపోకుండా ఎగుమతి నాణ్యతతో 40 టన్నులు సాధించే విధానం.',
      videoDescriptionEn: 'Staking tomatoes with bamboo and wire trellises prevents fruit blemish, fungal rot and triples productivity.',
      keyTakeawaysTe: [
        'నాటిన 25 రోజులకే మొదటి తాళ్ళ కట్టుడు పూర్తి చేయాలి.',
        'మొక్క కింది భాగంలో 1 అడుగు వరకు వచ్చే పిలకలను తొలగించాలి (Pruning).',
        'ట్రెల్లిస్ వల్ల మందుల పిచికారీ మరియు కాయల కోత అత్యంత సులభమవుతుంది.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'ట్రెల్లిస్ ఉపయోగాలు', titleEn: 'Benefits of Trellis'),
        VideoChapter(timestamp: '02:40', titleTe: 'కర్రలు & వైర్లు అమర్చడం', titleEn: 'Trellis Setup'),
        VideoChapter(timestamp: '05:30', titleTe: 'కొమ్మల కత్తిరింపు (Pruning)', titleEn: 'Pruning Techniques'),
      ],
    ),

    // 8. TURMERIC (పసుపు)
    const AgriVideoModel(
      id: 'v_turmeric_rhizome_rot',
      cropId: 'c_turmeric',
      titleTe: 'పసుపులో దుంప కుళ్ళు నివారణ & ఎత్తు మడుల సాగు విధానం',
      titleEn: 'Turmeric Rhizome Rot Control & Raised Bed Method',
      titleHi: 'हल्दी में कंद सड़न रोग नियंत्रण एवं मेड़ विधि',
      category: 'Pest Control',
      instructorName: 'Dr. సత్యనారాయణ (Dr. Satyanarayana)',
      instructorTitle: 'Spices Specialist, ICAR-IISR',
      duration: '07:50',
      viewsCount: '58.2K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=turmeric+rhizome+rot+control+telugu',
      sourceOrg: 'ICAR - Indian Institute of Spices Research',
      videoDescriptionTe: 'వర్షాకాలంలో పసుపు దుంపలు కుళ్ళిపోకుండా ట్రైకోడెర్మా జీవ నియంత్రణ మరియు మెటలాక్సిల్ ఎం.జడ్ ద్రావణాన్ని మొదళ్లలో పోసే (Drenching) విధానం.',
      videoDescriptionEn: 'Rhizome rot prevention in turmeric through drainage beds, bio-agents and chemical root drenching.',
      keyTakeawaysTe: [
        'ఎకరాకు 2 కిలోల ట్రైకోడెర్మాను 200 కిలోల పశువుల ఎరువులో కలిపి దుక్కిలో వేయాలి.',
        'తెగులు లక్షణాలు కనిపిస్తే రెడోమిల్ గోల్డ్ 2.5 గ్రా. లీటరు నీటికి కలిపి పాదుల వద్ద పోయాలి.',
        'చేనులో ఎట్టి పరిస్థితుల్లోనూ వర్షపు నీరు నిలవకుండా డ్రైనేజీ కాలువలు తీయాలి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'దుంప కుళ్ళు లక్షణాలు', titleEn: 'Rot Symptoms'),
        VideoChapter(timestamp: '02:15', titleTe: 'ట్రైకోడెర్మా వృద్ధి విధానం', titleEn: 'Trichoderma Prep'),
        VideoChapter(timestamp: '05:00', titleTe: 'పాదుల వద్ద ద్రావణం పోయడం', titleEn: 'Root Drenching Demo'),
      ],
    ),

    // 9. SOYBEAN (సోయాబీన్)
    const AgriVideoModel(
      id: 'v_soybean_seed_treatment',
      cropId: 'c_soybean',
      titleTe: 'సోయాబీన్ విత్తన శుద్ధి & మొదటి 30 రోజుల కలుపు నివారణ',
      titleEn: 'Soybean Inoculation & Early Weed Management',
      titleHi: 'सोयाबीन बीज उपचार एवं प्रारंभिक खरपतवार नियंत्रण',
      category: 'Cultivation',
      instructorName: 'Dr. మహేష్ గుప్తా (Dr. Mahesh Gupta)',
      instructorTitle: 'Principal Scientist, ICAR-IISR Indore',
      duration: '06:30',
      viewsCount: '34.5K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1599818816947-66c303102379?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=soybean+cultivation+telugu+farming',
      sourceOrg: 'ICAR - Indian Institute of Soybean Research',
      videoDescriptionTe: 'రైజోబియం మరియు పీఎస్‌బీ కల్చర్‌తో విత్తన శుద్ధి చేయడం మరియు విత్తిన వెంటనే వాడే కలుపు మందులతో అధిక దిగుబడి సాధించే పద్ధతి.',
      videoDescriptionEn: 'Bio-fertilizer seed inoculation and pre-emergence herbicide application in soybean.',
      keyTakeawaysTe: [
        'కిలో విత్తనానికి 5 గ్రా. రైజోబియం జపోనికమ్ కల్చర్ కలపాలి.',
        'విత్తిన 48 గంటల్లోపు పెండిమిథాలిన్ ఎకరాకు 1 లీటరు పిచికారీ చేయాలి.',
        'ఆకుముడత మరియు కాండపు ఈగ రాకుండా ఇమిడాక్లోప్రిడ్‌తో శుద్ధి తప్పనిసరి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:15', titleTe: 'రైజోబియం శుద్ధి డెమో', titleEn: 'Seed Inoculation'),
        VideoChapter(timestamp: '02:30', titleTe: 'కలుపు మందు స్ప్రే జాగ్రత్తలు', titleEn: 'Pre-emergence Herbicide'),
        VideoChapter(timestamp: '04:40', titleTe: 'మొలక శాతం రక్షణ', titleEn: 'Germination Care'),
      ],
    ),

    // 10. SUGARCANE (చెరకు)
    const AgriVideoModel(
      id: 'v_sugarcane_single_bud',
      cropId: 'c_sugarcane',
      titleTe: 'చెరకులో సింగిల్ బడ్ చిప్ నారు పద్ధతి - 85% విత్తనం ఆదా',
      titleEn: 'Single Bud Settlings in Sugarcane - 85% Seed Saving',
      titleHi: 'गन्ने में सिंगल बड चिप से नर्सरी एवं रोपण तकनीक',
      category: 'Cultivation',
      instructorName: 'Dr. రామచంద్రన్ (Dr. Ramachandran)',
      instructorTitle: 'Agronomist, ICAR-SBI Coimbatore',
      duration: '08:10',
      viewsCount: '46.7K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=sugarcane+single+bud+method+telugu',
      sourceOrg: 'ICAR - Sugarcane Breeding Institute',
      videoDescriptionTe: 'సాంప్రదాయకంగా 3-4 టన్నుల చెరకు విత్తే బదులుగా బడ్ చిప్పర్ మెషీన్‌తో కళ్లను వేరుచేసి ప్రోట్రేలలో పెంచి ఎకరానికి 50-60 టన్నుల బరువు సాధించే టెక్నిక్.',
      videoDescriptionEn: 'Single bud chip nursery raising and 5-foot furrow transplanting with drip fertigation.',
      keyTakeawaysTe: [
        'ఎకరానికి కేవలం 5 క్వింటాళ్ల విత్తన చెరకు సరిపోతుంది.',
        '25-30 రోజుల నారును 5 అడుగుల ఎడంలో బోదెలపై నాటాలి.',
        'మొక్క మొదళ్లలో ఎక్కువ పిలకలు వచ్చి చెరకు కర్ర లావుగా తయారవుతుంది.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'బడ్ చిప్పింగ్ ప్రదర్శన', titleEn: 'Bud Chipping Machine'),
        VideoChapter(timestamp: '02:40', titleTe: 'ప్రోట్రేలలో నారు పెంపకం', titleEn: 'Pro-tray Nursery'),
        VideoChapter(timestamp: '05:20', titleTe: 'చేనులో నాటడం & డ్రిప్ సేద్యం', titleEn: 'Transplanting in Field'),
      ],
    ),

    // 11. ONION (ఉల్లి)
    const AgriVideoModel(
      id: 'v_onion_nursery',
      cropId: 'c_onion',
      titleTe: 'ఉల్లిలో ఎత్తు మడులపై నారు పెంపకం & తలమచ్చల నివారణ',
      titleEn: 'Raised Bed Onion Nursery & Purple Blotch Control',
      titleHi: 'प्याज नर्सरी तैयार करना एवं पर्पल ब्लॉच रोग नियंत्रण',
      category: 'Cultivation',
      instructorName: 'Dr. శైలేష్ కుమార్ (Dr. Shailesh Kumar)',
      instructorTitle: 'Senior Scientist, ICAR-DOGR Pune',
      duration: '07:30',
      viewsCount: '41.2K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=onion+nursery+raising+telugu',
      sourceOrg: 'ICAR - Directorate of Onion and Garlic Research',
      videoDescriptionTe: 'వర్షాకాలంలో ఉల్లి నారు కుళ్ళకుండా ఎత్తు మడులపై నాటి 45 రోజులకు ప్రధాన పొలంలో మార్పిడి చేసే విధానం మరియు తలమచ్చల తెగులు నివారణ.',
      videoDescriptionEn: 'Best practices for healthy onion seedlings on raised nursery beds and purple blotch fungicidal sprays.',
      keyTakeawaysTe: [
        'నారుమడి ఎత్తు 15 సెం.మీ ఉండేలా తయారుచేయాలి.',
        'నారు పీకే 3 రోజుల ముందు ఇమిడాక్లోప్రిడ్ మరియు మాంకోజెబ్ స్ప్రే చేయండి.',
        'నారు కొనలను కొద్దిగా కత్తిరించి నాటడం వల్ల మొక్కలు త్వరగా నిలదొక్కుకుంటాయి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'నారుమడి తయారీ', titleEn: 'Nursery Bed Prep'),
        VideoChapter(timestamp: '02:30', titleTe: 'విత్తే పద్ధతి & కప్పి ఉంచడం', titleEn: 'Sowing & Mulching'),
        VideoChapter(timestamp: '05:00', titleTe: 'నారు పీకడం & నాటడం', titleEn: 'Transplanting Care'),
      ],
    ),

    // 12. MANGO (మామిడి)
    const AgriVideoModel(
      id: 'v_mango_pruning',
      cropId: 'c_mango',
      titleTe: 'మామిడిలో పూత సమృద్ధిగా వచ్చేందుకు ప్రూనింగ్ & కాయ రాలకుండా సలహాలు',
      titleEn: 'Mango Canopy Pruning & Flower Drop Prevention',
      titleHi: 'आम में छंटाई एवं फूल झड़ने की रोकथाम',
      category: 'Cultivation',
      instructorName: 'Dr. శివప్రసాద్ (Dr. Shiva Prasad)',
      instructorTitle: 'Horticulture Specialist, ICAR-CISH',
      duration: '08:50',
      viewsCount: '73.1K',
      thumbnailUrl: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&q=80',
      youtubeUrl: 'https://www.youtube.com/results?search_query=mango+pruning+flowering+telugu',
      sourceOrg: 'ICAR - Central Institute for Subtropical Horticulture',
      videoDescriptionTe: 'కోత పూర్తయిన తర్వాత ఎండు కొమ్మలను తొలగించడం మరియు సెప్టెంబర్-అక్టోబర్‌లో ప్యాక్లోబ్యూట్రజోల్ వాడి క్రమం తప్పకుండా ప్రతి సంవత్సరం పూత తెప్పించే టెక్నిక్.',
      videoDescriptionEn: 'Post-harvest pruning and paclobutrazol root zone application for alternate bearing management in mango.',
      keyTakeawaysTe: [
        'చెట్టు లోపలికి సూర్యరశ్మి సోకేలా సెంటర్ ఓపెనింగ్ ప్రూనింగ్ చేయాలి.',
        'పూత దశలో తేనెమంచు పురుగు నివారణకు థయామిథోక్సామ్ 0.3 గ్రా. లీటరు నీటికి స్ప్రే చేయండి.',
        'చిన్న బఠానీ గింజ సైజు కాయలు ఉన్నప్పుడు ప్లానోఫిక్స్ 1 మి.లీ 4.5 లీటర్ల నీటికి కలిపి పిచికారీ చేయాలి.',
      ],
      chapters: [
        VideoChapter(timestamp: '00:20', titleTe: 'ప్రూనింగ్ సమయం & పద్ధతి', titleEn: 'Pruning Techniques'),
        VideoChapter(timestamp: '03:10', titleTe: 'పూత ప్రేరేపణ సలహాలు', titleEn: 'Flower Induction'),
        VideoChapter(timestamp: '06:00', titleTe: 'పిందె రాలకుండా పిచికారీ', titleEn: 'Fruit Retention Spray'),
      ],
    ),
  ];

  static List<AgriVideoModel> getVideosForCrop(String cropId) {
    final list = allCropVideos.where((v) => v.cropId == cropId).toList();
    if (list.isNotEmpty) return list;
    return allCropVideos.take(2).toList();
  }
}
