class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'appName': 'Rythu Mitra',
      'appTagline': 'Smart Farming. Better Decisions. Better Harvest.',
      'welcomeFarmer': 'Welcome, Farmer',
      'subWelcome': "Let's make farming smarter and more profitable.",
      'selectLanguage': 'Select Your Language',
      'telugu': 'Telugu',
      'english': 'English',
      'hindi': 'Hindi',
      'continueBtn': 'Continue',
      'continueGoogle': 'Continue with Google',
      'continuePhone': 'Continue with Phone Number',
      'enterPhone': 'Enter Mobile Number',
      'verifyOtp': 'Verify OTP',
      'otpSentTo': 'Enter the 6-digit code sent to',
      'resendOtp': 'Resend OTP',
      'verifyAndLogin': 'Verify & Login',
      'skipForNow': 'Explore App First',
      'home': 'Home',
      'crops': 'Crops',
      'market': 'Market',
      'diagnose': 'Diagnose',
      'profile': 'Profile',
      'goodMorning': 'Good Morning',
      'goodAfternoon': 'Good Afternoon',
      'goodEvening': 'Good Evening',
      'farmer': 'Farmer',
      'searchPlaceholder': 'Search crops, diseases, fertilizers, prices...',
      'weatherCardTitle': 'Live Weather & Farm Advisory',
      'rainExpectedTomorrow': 'Rain expected tomorrow (30mm). Hold off irrigation & pesticide sprays.',
      'irrigationNotRequired': 'Soil moisture adequate. Irrigation not required today.',
      'myFarm': 'My Active Farm',
      'currentCrop': 'Current Crop',
      'area': 'Area',
      'sowingDate': 'Sowing Date',
      'cropStage': 'Crop Stage',
      'stageSeedling': 'Seedling',
      'stageVegetative': 'Vegetative',
      'stageFlowering': 'Flowering',
      'stageHarvest': 'Harvest',
      'quickActions': 'Quick Actions & Tools',
      'cropGuide': 'Crop Guide',
      'cropGuideSub': 'Complete cultivation guidance',
      'fertilizer': 'Fertilizer & Nutrition',
      'fertilizerSub': 'NPK & micronutrient calculator',
      'diseaseAI': 'AI Disease Scan',
      'diseaseAISub': 'Instant leaf pest diagnosis',
      'marketPrices': 'Mandi Prices',
      'marketPricesSub': 'Live APMC market rates & trends',
      'govtSchemes': 'Govt Schemes',
      'govtSchemesSub': 'Subsidies & welfare benefits',
      'farmCalendar': 'Farm Calendar',
      'farmCalendarSub': 'Automated cultivation timeline',
      'expenseTracker': 'Expense Tracker',
      'expenseTrackerSub': 'Track farm costs & profits',
      'equipmentRental': 'Equipment Rental',
      'equipmentRentalSub': 'Tractors & tools nearby',
      'voiceAssistant': 'Voice Assistant',
      'voiceAssistantSub': 'Ask questions in your language',
      'organicFarming': 'Organic Farming',
      'organicFarmingSub': 'Natural pest control & compost',
      'community': 'Community Forum',
      'communitySub': 'Discuss with fellow farmers',
      'talkToExpert': 'Talk to Expert',
      'talkToExpertSub': 'Certified Agronomists',
      'smartIrrigation': 'Smart Irrigation',
      'smartIrrigationSub': 'Water requirement calculator',
      'satelliteHealth': 'Satellite Farm Health',
      'satelliteHealthSub': 'Simulated NDVI vegetation index',
      'seasonalCrops': 'Recommended for this Season',
      'viewGuide': 'View Guide',
      'days': 'days',
      'waterReq': 'Water Requirement',
      'expectedYield': 'Expected Yield',
      'todayPrices': "Today's Mandi Market Rates",
      'nearbyMarkets': 'Nearby Mandis',
      'priceChart': 'Price Trend (Last 30 Days)',
      'minPrice': 'Min Price',
      'maxPrice': 'Max Price',
      'avgPrice': 'Modal / Avg',
      'checkCrop': 'Check Your Crop Disease',
      'takePhoto': 'Take Photo',
      'uploadPhoto': 'Upload Photo',
      'describeProblem': 'Describe Problem',
      'analyzingCrop': 'AI Analyzing Crop Health...',
      'diagnosticDisclaimer': 'AI suggestions are general guidance. Consult agricultural extension officers for severe damage.',
      'emergencyHelpline': 'Kisan Call Centre: 1551 (Toll-Free)',
      'totalInvestment': 'Total Investment',
      'totalRevenue': 'Expected Revenue',
      'netProfit': 'Estimated Net Profit',
      'addExpense': 'Add New Expense',
      'save': 'Save',
      'cancel': 'Cancel',
      'filter': 'Filter',
      'all': 'All',
      'active': 'Active',
      'notifications': 'Notifications',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'logout': 'Sign Out',
      'viewDetails': 'View Details',
      'applyNow': 'Apply Officially',
      'krishiBazaar': 'Krishi Bazaar',
      'krishiBazaarSub': 'Buy certified seeds & inputs',
      'seasonLabel': 'Season',
      'durationLabel': 'Duration',
      'waterLabel': 'Water Requirement',
      'yieldLabel': 'Expected Yield',
      'soilLabel': 'Suitable Soil',
      'costLabel': 'Average Cost',
      'secOverview': 'Crop Overview',
      'secLandPrep': 'Land Preparation',
      'secSowing': 'Sowing Method & Spacing',
      'secFertilizer': 'Fertilizer Schedule',
      'secIrrigation': 'Irrigation Management',
      'secPest': 'Pest & Disease Control',
      'secHarvest': 'Harvesting & Storage',
      'secEconomics': 'Economics & Yield',
      'cultivationGuideTitle': 'Step-by-Step Cultivation Guide',
      'dosTitle': 'Recommended Practices (Do\'s)',
      'dontsTitle': 'Practices to Avoid (Don\'ts)',
      'dosDontsHeading': 'Farmer Advisory (Do\'s & Don\'ts)',
      'watchVideo': 'Watch Video Tutorial',
      'listenAudio': 'Listen to Cultivation Guide',
      'calcFertilizer': 'Calculate Fertilizer Dosage for this Crop',
      'calcFertilizerSub': 'Accurate NPK & micronutrient dosage calculator',
      'videoTutorials': 'Agricultural Video Tutorials',
      'viewAll': 'View All',
      'emergencyTitle': 'Kisan Emergency Helpline (24x7)',
      'emergencySubtitle': 'Free call to Agricultural Officer',
      'tollFree': 'Toll-Free 1551',
      'selectLocation': 'Select Your Location',
      'photoGalleryTitle': 'Crop Photos Gallery',
      'photoGallerySub': 'Interactive visual cultivation guides',
      'allFilter': 'All',
      'kharifFilter': 'Kharif',
      'rabiFilter': 'Rabi',
      'commercialFilter': 'Commercial',
      'summerFilter': 'Summer',
      'vegetableFilter': 'Vegetables',
      'speakingVoice': 'Speaking...',
      'listenVoice': 'Listen Aloud',
      'voiceAiBadge': 'Voice AI',
      'voiceAiDesc': 'Audio assistance for farmers',
      'keyTakeaways': 'Key Takeaways',
      'listenSummary': 'Listen to Video Summary',
      'views': 'views',
      'schemesTitle': 'Govt Schemes & Subsidies',
      'schemesSub': 'Verified State & Central Farmer Welfare Schemes',
      'searchSchemesPlaceholder': 'Search schemes, subsidies, loans...',
      'telanganaSchemes': 'Telangana Schemes',
      'centralSchemes': 'Central Schemes',
      'allSchemes': 'All Schemes',
      'subsidyFinder': 'Subsidy Calculator',
      'myApplications': 'My Applications',
      'findSchemesForMe': 'Find Schemes For Me',
      'findSchemesForMeSub': 'Check instant eligibility based on your land and crop',
      'checkEligibility': 'Check Eligibility',
      'verifiedOfficial': 'Official Source Verified',
      'viewDetailsApply': 'Full Details & Apply',
      'benefitsTitle': 'Benefits Provided',
      'eligibilityCriteria': 'Eligibility Criteria',
      'requiredDocs': 'Required Documents',
      'howToApplySteps': 'How to Apply (5 Steps)',
      'applyOnOfficialWebsite': 'Apply on Official Website',
      'deadlineRemaining': 'Days Remaining',
      'helpline': 'Helpline',
      'openPortal': 'Open Official Portal',
      'schemeDisclaimer': 'Disclaimer: Government scheme rules, amounts, and eligibility may vary. Always verify on the official government portal before applying.',
      'likelyEligible': 'Likely Eligible Based on Your Profile',
      'moreInfoRequired': 'Review Listed Criteria',
      'calculateSubsidy': 'Calculate Your Subsidy',
      'estimatedShare': 'Farmer Share',
      'govtSubsidyShare': 'Govt Subsidy',
      'totalEquipmentCost': 'Total Cost',
      'statusSubmitted': 'Submitted',
      'statusVerification': 'Under Verification',
      'statusApproved': 'Approved & Disbursed',
      'trackApplication': 'Track Application',
      'enterAckNumber': 'Enter Application / Passbook Number',
      'voiceScreenTitle': 'Krishi Mitra Voice AI',
      'voiceScreenSub': 'Ask any farming question by voice',
      'voiceLanguageNote': 'Speak in Telugu, Hindi or English',
      'voiceListening': 'Listening... Please speak now',
      'voiceSampleTitle': 'Sample Questions (Tap to try):',
      'voiceMicHint': 'Tap the microphone or select a sample question below',
      'voiceQ1': 'My cotton leaves are turning yellow. What to do?',
      'voiceA1': 'Yellow lower leaves in cotton indicate Nitrogen or Magnesium deficiency.\n\nSolution:\n1. Apply 25-30 kg Urea per acre.\n2. For immediate relief, spray 2% Urea or Magnesium Sulphate solution (10g/litre).',
      'voiceQ2': 'Which medicine to use for rice leaf blast disease?',
      'voiceA2': 'For Rice Leaf Blast:\n\n1. Mix 0.6g Tricyclazole (Beam/Ban) per litre of water.\n2. Reduce Nitrogen fertilizer application.\n3. Spray only after morning dew dries.',
      'voiceQ3': "What is today's cotton price at Warangal market?",
      'voiceA3': "Today's Warangal Enumamula Market Yard cotton price:\n\nMax: ₹7,950 / Quintal\nAverage: ₹7,750 / Quintal\nTrend: +₹150 higher than yesterday.",
      'communityTitle': 'Farmer Community Forum',
      'communityPostBtn': 'Post Question',
      'communityLikes': 'likes',
      'communityReplies': 'replies',
      'communityTrending': 'Trending Discussions',
      'communityShare': 'Share Your Experience',
      'equipmentTitle': 'Equipment & Tractor Rental',
      'equipmentBook': 'Book Now',
      'equipmentAvail': 'Available',
      'equipmentPerDay': '/day',
      'equipmentNearby': 'Nearby Equipment',
      'marketplaceTitle': 'Krishi Bazaar — Agri Marketplace',
      'marketplaceCart': 'Add to Cart',
      'marketplaceCertified': 'Certified',
      'marketplaceSeeds': 'Seeds',
      'marketplaceFertilizers': 'Fertilizers',
      'marketplacePesticides': 'Pesticides',
      'marketplaceTools': 'Farm Tools',
      'irrTodayNeed': 'Today\'s Water Requirement',
      'irrWeatherOpt': 'Weather Optimized',
      'irrLitresDay': 'Litres / Day',
      'irrPumpTime': 'Pump Run Time',
      'irrHours': 'Hours (5HP Drip)',
      'irrRainAdvisory': 'Rain expected tomorrow. You can reduce today\'s irrigation by 50%.',
      'irrParams': 'Adjust Farm Parameters:',
      'irrFarmArea': 'Farm Area:',
      'irrAcres': 'Acres',
      'irrTypeLabel': 'Irrigation Method',
      'irrDrip': 'Drip Irrigation',
      'irrSprinkler': 'Sprinkler Irrigation',
      'irrFlood': 'Flood / Furrow Irrigation',
      'irrSoilLabel': 'Soil Type',
      'soilBlack': 'Black Cotton Soil',
      'soilRed': 'Red Sandy Loam',
      'soilClay': 'Clayey Soil',
      'irrStageLabel': 'Crop Growth Stage',
      'stageBoll': 'Boll / Fruit Development',
    },
    'te': {
      'appName': 'రైతు మిత్ర',
      'appTagline': 'స్మార్ట్ వ్యవసాయం • సరైన నిర్ణయం • సమృద్ధి పంట',
      'welcomeFarmer': 'రైతు సోదరులకు స్వాగతం',
      'subWelcome': 'వ్యవసాయాన్ని మరింత లాభదాయకంగా మరియు స్మార్ట్‌గా మార్చుకుందాం.',
      'selectLanguage': 'మీ భాషను ఎంచుకోండి',
      'telugu': 'తెలుగు',
      'english': 'ఆంగ్లం',
      'hindi': 'హిందీ',
      'continueBtn': 'ముందుకు సాగండి',
      'continueGoogle': 'Google తో కొనసాగండి',
      'continuePhone': 'ఫోన్ నంబర్ తో లాగిన్ అవ్వండి',
      'enterPhone': 'మొబైల్ నంబర్ నమోదు చేయండి',
      'verifyOtp': 'OTP ని ధృవీకరించండి',
      'otpSentTo': 'మీ ఫోన్‌కు పంపిన 6 అంకెల కోడ్‌ను నమోదు చేయండి',
      'resendOtp': 'OTP మళ్లీ పంపండి',
      'verifyAndLogin': 'ధృవీకరించి ప్రవేశించండి',
      'skipForNow': 'యాప్‌ను నేరుగా చూడండి',
      'home': 'హోమ్',
      'crops': 'పంటలు',
      'market': 'మార్కెట్',
      'diagnose': 'వ్యాధి గుర్తింపు',
      'profile': 'ప్రొఫైల్',
      'goodMorning': 'శుభోదయం',
      'goodAfternoon': 'శుభ మధ్యాహ్నం',
      'goodEvening': 'శుభ సాయంత్రం',
      'farmer': 'రైతు గారు',
      'searchPlaceholder': 'పంటలు, తెగుళ్లు, ఎరువులు, మార్కెట్ ధరలు వెతకండి...',
      'weatherCardTitle': 'వాతావరణం & వ్యవసాయ సలహా',
      'rainExpectedTomorrow': 'రేపు భారీ వర్షం (30mm) పడే అవకాశం ఉంది. మందుల పిచికారీ, నీటిపారుదల వాయిదా వేయండి.',
      'irrigationNotRequired': 'భూమిలో తగినంత తేమ ఉంది. నేడు నీరు పెట్టవలసిన అవసరం లేదు.',
      'myFarm': 'నా తోట / పొలం',
      'currentCrop': 'ప్రస్తుత పంట',
      'area': 'విస్తీర్ణం',
      'sowingDate': 'విత్తిన తేదీ',
      'cropStage': 'పంట దశ',
      'stageSeedling': 'మొలక దశ',
      'stageVegetative': 'శాఖీయ పెరుగుదల',
      'stageFlowering': 'పూత దశ',
      'stageHarvest': 'కోత దశ',
      'quickActions': 'ముఖ్యమైన సాధనాలు & సేవలు',
      'cropGuide': 'సాగు సమగ్ర సమాచారం',
      'cropGuideSub': 'విత్తనం నుండి కోత వరకు',
      'fertilizer': 'ఎరువుల యాజమాన్యం',
      'fertilizerSub': 'NPK & సూక్ష్మపోషకాల మోతాదు',
      'diseaseAI': 'AI రోగ నిర్ధారణ',
      'diseaseAISub': 'ఆకు ఫోటోతో తెగులు గుర్తింపు',
      'marketPrices': 'లైవ్ మార్కెట్ ధరలు',
      'marketPricesSub': 'మార్కెట్ యార్డ్ తాజా రేట్లు',
      'govtSchemes': 'ప్రభుత్వ పథకాలు',
      'govtSchemesSub': 'రైతు భరోసా, పీఎం కిసాన్ వివరాలు',
      'farmCalendar': 'వ్యవసాయ క్యాలెండర్',
      'farmCalendarSub': 'రోజువారీ పనుల కాలపట్టిక',
      'expenseTracker': 'ఆదాయ-వ్యయాల లెక్కలు',
      'expenseTrackerSub': 'ఖర్చులు మరియు లాభాల రికార్డు',
      'equipmentRental': 'ట్రాక్టర్ & యంత్రాల అద్దె',
      'equipmentRentalSub': 'సమీపంలోని యంత్రాలు సులభంగా',
      'voiceAssistant': 'వాయిస్ అసిస్టెంట్',
      'voiceAssistantSub': 'మీ గొంతుతోనే ప్రశ్నలు అడగండి',
      'organicFarming': 'సేంద్రియ & ప్రకృతి వ్యవసాయం',
      'organicFarmingSub': 'జీవామృతం, నీమాస్త్రం తయారీ',
      'community': 'రైతు వేదిక',
      'communitySub': 'తోటి రైతులతో చర్చించండి',
      'talkToExpert': 'వ్యవసాయ శాస్త్రవేత్తలు',
      'talkToExpertSub': 'నిపుణులతో నేరుగా మాట్లాడండి',
      'smartIrrigation': 'స్మార్ట్ నీటి యాజమాన్యం',
      'smartIrrigationSub': 'ఎకరానికి అవసరమైన నీటి లెక్క',
      'satelliteHealth': 'ఉపగ్రహ పొలం ఆరోగ్యం',
      'satelliteHealthSub': 'NDVI శాటిలైట్ పచ్చదనం సూచిక',
      'seasonalCrops': 'ఈ సీజన్‌కు అనువైన పంటలు',
      'viewGuide': 'పూర్తి వివరాలు →',
      'days': 'రోజులు',
      'waterReq': 'నీటి అవసరం',
      'expectedYield': 'ఆశించే దిగుబడి',
      'todayPrices': 'నేటి మార్కెట్ ధరలు',
      'nearbyMarkets': 'సమీప మార్కెట్లు',
      'priceChart': 'గత 30 రోజుల ధరల మార్పు ధోరణి',
      'minPrice': 'కనిష్ట ధర',
      'maxPrice': 'గరిష్ట ధర',
      'avgPrice': 'సగటు ధర',
      'checkCrop': 'పంట ఆకు ఫోటో తీసి పరిశీలించండి',
      'takePhoto': 'కెమెరాతో ఫోటో తీయండి',
      'uploadPhoto': 'గ్యాలరీ నుండి ఎంచుకోండి',
      'describeProblem': 'సమస్యను మాటల్లో చెప్పండి',
      'analyzingCrop': 'AI తెగులును విశ్లేషిస్తోంది...',
      'diagnosticDisclaimer': 'ఈ ఫలితాలు సాధారణ ప్రాథమిక సమాచారం కోసం మాత్రమే. తీవ్రమైన నష్టాల్లో వ్యవసాయ అధికారిని సంప్రదించండి.',
      'emergencyHelpline': 'కిసాన్ కాల్ సెంటర్: 1551 - ఉచితం',
      'totalInvestment': 'మొత్తం ఖర్చు',
      'totalRevenue': 'ఆశించే రాబడి',
      'netProfit': 'అంచనా నికర లాభం',
      'addExpense': 'కొత్త ఖర్చును జోడించండి',
      'save': 'భద్రపరచండి',
      'cancel': 'రద్దు చేయండి',
      'filter': 'వడపోత',
      'all': 'అన్నీ',
      'active': 'క్రియాశీలకంగా ఉంది',
      'notifications': 'నోటిఫికేషన్లు',
      'darkMode': 'డార్క్ మోడ్',
      'language': 'భాష మార్పు',
      'logout': 'లాగ్ అవుట్',
      'viewDetails': 'పూర్తి వివరాలు',
      'applyNow': 'అధికారికంగా దరఖాస్తు చేసుకోండి',
      'krishiBazaar': 'కృషి బజార్',
      'krishiBazaarSub': 'నాణ్యమైన విత్తనాలు, ఎరువుల కొనుగోలు',
      'seasonLabel': 'సీజన్',
      'durationLabel': 'కాలపరిమితి',
      'waterLabel': 'నీటి అవసరం',
      'yieldLabel': 'ఆశించే దిగుబడి',
      'soilLabel': 'అనువైన నేల',
      'costLabel': 'సగటు పెట్టుబడి',
      'secOverview': 'పంట అవలోకనం',
      'secLandPrep': 'నేల తయారీ & దుక్కులు',
      'secSowing': 'విత్తే పద్ధతి & సాళ్ల దూరం',
      'secFertilizer': 'ఎరువుల యాజమాన్యం',
      'secIrrigation': 'నీటి యాజమాన్యం & తడులు',
      'secPest': 'పురుగులు & తెగుళ్ల నివారణ',
      'secHarvest': 'కోత & నిల్వ పద్ధతులు',
      'secEconomics': 'పెట్టుబడి & దిగుబడి లెక్కలు',
      'cultivationGuideTitle': 'సాగు సమగ్ర మార్గదర్శకాలు',
      'dosTitle': 'ఏమి చేయాలి?',
      'dontsTitle': 'ఏమి చేయకూడదు?',
      'dosDontsHeading': 'రైతు మిత్ర సూచనలు',
      'watchVideo': 'వ్యవసాయ వీడియో శిక్షణ చూడండి',
      'listenAudio': 'సాగు సమాచారం వినండి',
      'calcFertilizer': 'ఈ పంటకు ఎరువుల మోతాదును లెక్కించండి',
      'calcFertilizerSub': 'NPK & సూక్ష్మపోషకాల ఖచ్చితమైన మోతాదు క్యాలిక్యులేటర్',
      'videoTutorials': 'వ్యవసాయ వీడియో శిక్షణ',
      'viewAll': 'అన్నీ చూడండి',
      'emergencyTitle': 'కిసాన్ అత్యవసర హెల్ప్‌లైన్',
      'emergencySubtitle': 'వ్యవసాయ అధికారికి ఉచిత కాల్',
      'tollFree': 'ఉచిత కాల్ 1551',
      'selectLocation': 'మీ ప్రాంతాన్ని ఎంచుకోండి',
      'photoGalleryTitle': 'పంటల ఫోటో గ్యాలరీ',
      'photoGallerySub': 'సాగు వివరాలు చూడటానికి ఫోటోపై తాకండి',
      'allFilter': 'అన్నీ',
      'kharifFilter': 'ఖరీఫ్',
      'rabiFilter': 'రబీ',
      'commercialFilter': 'వాణిజ్య పంటలు',
      'summerFilter': 'వేసవి',
      'vegetableFilter': 'కూరగాయలు',
      'speakingVoice': 'వినిపిస్తోంది...',
      'listenVoice': 'చదివి వినిపించండి',
      'voiceAiBadge': 'వాయిస్ AI',
      'voiceAiDesc': 'చదవలేని రైతుల కోసం ఆడియో సదుపాయం',
      'views': 'వీక్షణలు',
      'schemesTitle': 'ప్రభుత్వ పథకాలు & సబ్సిడీలు',
      'schemesSub': 'ధృవీకరించబడిన రాష్ట్ర మరియు కేంద్ర రైతు సంక్షేమ పథకాలు',
      'searchSchemesPlaceholder': 'పథకాలు, సబ్సిడీలు, రుణాల కోసం వెతకండి...',
      'telanganaSchemes': 'తెలంగాణ పథకాలు',
      'centralSchemes': 'కేంద్ర పథకాలు',
      'allSchemes': 'అన్ని పథకాలు',
      'subsidyFinder': 'సబ్సిడీ కాలిక్యులేటర్',
      'myApplications': 'నా దరఖాస్తులు',
      'findSchemesForMe': 'నా పొలానికి తగిన పథకాలు',
      'findSchemesForMeSub': 'మీ భూమి విస్తీర్ణం, పంట ఆధారంగా అర్హతలను క్షణాల్లో సరిచూసుకోండి',
      'checkEligibility': 'అర్హతను తనిఖీ చేయండి',
      'verifiedOfficial': 'అధికారిక మూలం ధృవీకరించబడింది',
      'viewDetailsApply': 'పూర్తి వివరాలు & దరఖాస్తు',
      'benefitsTitle': 'లభించే ప్రయోజనాలు',
      'eligibilityCriteria': 'అర్హత ప్రమాణాలు',
      'requiredDocs': 'అవసరమైన పత్రాలు',
      'howToApplySteps': 'దరఖాస్తు చేసుకునే 5 దశలు',
      'applyOnOfficialWebsite': 'అధికారిక వెబ్‌సైట్‌లో దరఖాస్తు చేయండి',
      'deadlineRemaining': 'రోజులు మిగిలి ఉన్నాయి',
      'helpline': 'హెల్ప్‌లైన్',
      'openPortal': 'అధికారిక పోర్టల్ ఓపెన్ చేయండి',
      'schemeDisclaimer': 'గమనిక: ప్రభుత్వ పథకాల నిబంధనలు మరియు గడువులు మారవచ్చు. దరఖాస్తు చేసే ముందు ఎల్లప్పుడూ అధికారిక ప్రభుత్వ పోర్టల్‌లో తాజా సమాచారాన్ని సరిచూసుకోండి.',
      'likelyEligible': 'మీ వివరాల ప్రకారం అర్హత కలిగిన అవకాశం ఉంది',
      'moreInfoRequired': 'నిర్దేశిత నిబంధనలను పరిశీలించండి',
      'calculateSubsidy': 'మీ సబ్సిడీని లెక్కించండి',
      'estimatedShare': 'రైతు చెల్లించాల్సిన వాటా',
      'govtSubsidyShare': 'ప్రభుత్వ సబ్సిడీ',
      'totalEquipmentCost': 'మొత్తం అంచనా ఖర్చు',
      'statusSubmitted': 'సమర్పించబడింది',
      'statusVerification': 'క్షేత్ర పరిశీలనలో ఉంది',
      'statusApproved': 'ఆమోదించబడి నిధులు జమ అయ్యాయి',
      'trackApplication': 'దరఖాస్తు స్థితిని తెలుసుకోండి',
      'enterAckNumber': 'దరఖాస్తు సంఖ్య / పాస్‌బుక్ నంబర్ నమోదు చేయండి',
      'voiceScreenTitle': 'కృషి మిత్ర వాయిస్ AI',
      'voiceScreenSub': 'ఏ వ్యవసాయ ప్రశ్నయినా గొంతుతో అడగండి',
      'voiceLanguageNote': 'తెలుగు, హిందీ లేదా ఇంగ్లీష్‌లో మాట్లాడండి',
      'voiceListening': 'వినబడుతోంది... మాట్లాడండి',
      'voiceSampleTitle': 'నమూనా ప్రశ్నలు (నొక్కి అడగండి):',
      'voiceMicHint': 'మైక్రోఫోన్ నొక్కండి లేదా కింద నమూనా ప్రశ్న ఎంచుకోండి',
      'voiceQ1': 'నా పత్తి ఆకులు పసుపుగా మారుతున్నాయి. ఏమి చేయాలి?',
      'voiceA1': 'పత్తిలో దిగువ ఆకులు పసుపు రంగులోకి మారితే అది నత్రజని లేదా మెగ్నీషియం లోపం.\n\nపరిష్కారం:\n1. ఎకరాకు 25-30 కిలోల యూరియా వేయండి.\n2. 2% యూరియా లేదా మెగ్నీషియం సల్ఫేట్ (10g/లీ) పిచికారీ చేయండి.',
      'voiceQ2': 'వరిలో అగ్గితెగులు నివారణకు ఏ మందు వాడాలి?',
      'voiceA2': 'వరి అగ్గితెగులు నివారణకు:\n\n1. ట్రైసైక్లాజోల్ (0.6g/లీ) వాడండి.\n2. నత్రజని ఎరువులు తగ్గించండి.\n3. మంచు ఆరిన తర్వాత పిచికారీ చేయండి.',
      'voiceQ3': 'ఈరోజు వరంగల్ మార్కెట్‌లో పత్తి ధర ఎంత?',
      'voiceA3': 'వరంగల్ మార్కెట్ నేడు పత్తి ధర:\n\nగరిష్ట: ₹7,950 / క్వింటాల్\nసగటు: ₹7,750 / క్వింటాల్\nధోరణి: నిన్నటి కంటే +₹150 పెరిగింది.',
      'communityTitle': 'రైతు వేదిక - చర్చల వేదిక',
      'communityPostBtn': 'ప్రశ్న అడగండి',
      'communityLikes': 'మెచ్చుకున్నారు',
      'communityReplies': 'సమాధానాలు',
      'communityTrending': 'ఇప్పుడు చర్చలో ఉన్నవి',
      'communityShare': 'మీ అనుభవం పంచండి',
      'equipmentTitle': 'ట్రాక్టర్ & యంత్రాల అద్దె',
      'equipmentBook': 'బుక్ చేయండి',
      'equipmentAvail': 'అందుబాటులో ఉంది',
      'equipmentPerDay': '/రోజుకు',
      'equipmentNearby': 'సమీప యంత్రాలు',
      'marketplaceTitle': 'కృషి బజార్ - వ్యవసాయ మార్కెట్',
      'marketplaceCart': 'కార్ట్‌కు జోడించు',
      'marketplaceCertified': 'ధృవీకరించబడింది',
      'marketplaceSeeds': 'విత్తనాలు',
      'marketplaceFertilizers': 'ఎరువులు',
      'marketplacePesticides': 'మందులు',
      'marketplaceTools': 'వ్యవసాయ పరికరాలు',
      'irrTodayNeed': 'నేటి నీటి అవసరం',
      'irrWeatherOpt': 'వాతావరణ సూచన',
      'irrLitresDay': 'లీటర్లు / రోజుకు',
      'irrPumpTime': 'మోటార్ నడిపే సమయం',
      'irrHours': 'గంటలు - 5HP డ్రిప్',
      'irrRainAdvisory': 'రేపు వర్షం పడే అవకాశం ఉంది. ఈరోజు నీటిపారుదల 50% తగ్గించవచ్చు.',
      'irrParams': 'పొలం వివరాలు సర్దుబాటు చేయండి:',
      'irrFarmArea': 'తోట విస్తీర్ణం:',
      'irrAcres': 'ఎకరాలు',
      'irrTypeLabel': 'నీటిపారుదల పద్ధతి',
      'irrDrip': 'బిందు సేద్యం',
      'irrSprinkler': 'తుంపర సేద్యం',
      'irrFlood': 'సాళ్ల పద్ధతి',
      'irrSoilLabel': 'నేల రకం',
      'soilBlack': 'నల్లరేగడి నేల',
      'soilRed': 'ఎర్ర గరప నేల',
      'soilClay': 'బంకమన్ను నేల',
      'irrStageLabel': 'పంట పెరుగుదల దశ',
      'stageBoll': 'కాయ / గింజ పెరుగుదల దశ',
    },
    'hi': {
      'appName': 'रैतु मित्र',
      'appTagline': 'स्मार्ट खेती • सही निर्णय • उत्तम उपज',
      'welcomeFarmer': 'किसान भाई का स्वागत है',
      'subWelcome': 'खेती को बनाएं और अधिक आसान और लाभदायक।',
      'selectLanguage': 'अपनी भाषा चुनें',
      'telugu': 'तेलुगु',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिन्दी',
      'continueBtn': 'आगे बढ़ें',
      'continueGoogle': 'Google से जारी रखें',
      'continuePhone': 'मोबाइल नंबर से लॉगिन करें',
      'enterPhone': 'मोबाइल नंबर दर्ज करें',
      'verifyOtp': 'ओटीपी सत्यापित करें',
      'otpSentTo': 'आपके फोन पर भेजे गए 6 अंकों का कोड डालें',
      'resendOtp': 'ओटीपी पुनः भेजें',
      'verifyAndLogin': 'सत्यापित करके प्रवेश करें',
      'skipForNow': 'पहले ऐप देखें',
      'home': 'होम',
      'crops': 'फसलें',
      'market': 'मंडी भाव',
      'diagnose': 'रोग पहचान',
      'profile': 'प्रोफाइल',
      'goodMorning': 'सुप्रभात',
      'goodAfternoon': 'शुभ दोपहर',
      'goodEvening': 'शुभ संध्या',
      'farmer': 'किसान जी',
      'searchPlaceholder': 'फसल, कीट, खाद, मंडी भाव खोजें...',
      'weatherCardTitle': 'मौसम और कृषि परामर्श',
      'rainExpectedTomorrow': 'कल बारिश (30mm) की संभावना है। कीटनाशक छिड़काव व सिंचाई टालें।',
      'irrigationNotRequired': 'मिट्टी में पर्याप्त नमी है। आज सिंचाई की आवश्यकता नहीं है।',
      'myFarm': 'मेरा खेत',
      'currentCrop': 'वर्तमान फसल',
      'area': 'क्षेत्रफल',
      'sowingDate': 'बुवाई की तारीख',
      'cropStage': 'फसल चरण',
      'stageSeedling': 'अंकुरण',
      'stageVegetative': 'वृद्धि चरण',
      'stageFlowering': 'फूल आना',
      'stageHarvest': 'कटाई चरण',
      'quickActions': 'त्वरित सेवाएं एवं उपकरण',
      'cropGuide': 'फसल मार्गदर्शिका',
      'cropGuideSub': 'बुवाई से कटाई तक संपूर्ण जानकारी',
      'fertilizer': 'खाद एवं पोषण',
      'fertilizerSub': 'NPK व सूक्ष्म पोषक मात्रा कैलकुलेटर',
      'diseaseAI': 'AI रोग पहचान',
      'diseaseAISub': 'पत्ती की फोटो से कीट पहचानें',
      'marketPrices': 'मंडी भाव',
      'marketPricesSub': 'निकटतम मंडियों के ताज़ा भाव',
      'govtSchemes': 'सरकारी योजनाएं',
      'govtSchemesSub': 'पीएम किसान व कृषि सब्सिडी',
      'farmCalendar': 'कृषि कैलेंडर',
      'farmCalendarSub': 'दैनिक कृषि कार्यों की समय-सारणी',
      'expenseTracker': 'खर्च व आय खाता',
      'expenseTrackerSub': 'खेती की लागत व मुनाफे का हिसाब',
      'equipmentRental': 'उपकरण व ट्रैक्टर किराया',
      'equipmentRentalSub': 'आस-पास उपलब्ध कृषि यंत्र',
      'voiceAssistant': 'ध्वनि सहायक',
      'voiceAssistantSub': 'अपनी भाषा में बोलकर पूछें',
      'organicFarming': 'जैविक खेती',
      'organicFarmingSub': 'जीवामृत व प्राकृतिक कीटनाशक',
      'community': 'किसान मंच',
      'communitySub': 'अन्य किसानों से अनुभव साझा करें',
      'talkToExpert': 'कृषि वैज्ञानिक से बात',
      'talkToExpertSub': 'विशेषज्ञों से सीधी सलाह',
      'smartIrrigation': 'स्मार्ट सिंचाई',
      'smartIrrigationSub': 'प्रति एकड़ सटीक जल आवश्यकता',
      'satelliteHealth': 'सैटेलाइट से खेत की सेहत',
      'satelliteHealthSub': 'NDVI उपग्रह वनस्पति सूचकांक',
      'seasonalCrops': 'इस मौसम की प्रमुख फसलें',
      'viewGuide': 'मार्गदर्शिका देखें',
      'days': 'दिन',
      'waterReq': 'जल आवश्यकता',
      'expectedYield': 'अनुमानित पैदावार',
      'todayPrices': 'आज के ताज़ा मंडी भाव',
      'nearbyMarkets': 'निकटतम मंडियां',
      'priceChart': 'मूल्य रुझान - पिछले 30 दिन',
      'minPrice': 'न्यूनतम',
      'maxPrice': 'अधिकतम',
      'avgPrice': 'औसत भाव',
      'checkCrop': 'अपनी फसल की जांच करें',
      'takePhoto': 'कैमरे से फोटो लें',
      'uploadPhoto': 'गैलरी से चुनें',
      'describeProblem': 'बोलकर समस्या बताएं',
      'analyzingCrop': 'AI फसल की जांच कर रहा है...',
      'diagnosticDisclaimer': 'यह सुझाव प्राथमिक जानकारी हैं। गंभीर क्षति में कृषि अधिकारी से संपर्क करें।',
      'emergencyHelpline': 'किसान कॉल सेंटर: 1551 - टोल-फ्री',
      'totalInvestment': 'कुल लागत',
      'totalRevenue': 'अनुमानित आय',
      'netProfit': 'शुद्ध मुनाफा',
      'addExpense': 'नया खर्च जोड़ें',
      'save': 'सुरक्षित करें',
      'cancel': 'रद्द करें',
      'filter': 'फ़िल्टर',
      'all': 'सभी',
      'active': 'सक्रिय',
      'notifications': 'सूचनाएं',
      'darkMode': 'डार्क मोड',
      'language': 'भाषा बदलें',
      'logout': 'लॉग आउट',
      'viewDetails': 'विवरण देखें',
      'applyNow': 'आधिकारिक आवेदन करें',
      'krishiBazaar': 'कृषि बाज़ार',
      'krishiBazaarSub': 'प्रमाणित बीज व खाद खरीदें',
      'seasonLabel': 'मौसम',
      'durationLabel': 'अवधि',
      'waterLabel': 'जल आवश्यकता',
      'yieldLabel': 'अनुमानित पैदावार',
      'soilLabel': 'उपयुक्त मिट्टी',
      'costLabel': 'औसत लागत',
      'secOverview': 'फसल अवलोकन',
      'secLandPrep': 'खेत की तैयारी',
      'secSowing': 'बुवाई विधि व दूरी',
      'secFertilizer': 'उर्वरक प्रबंधन',
      'secIrrigation': 'सिंचाई प्रबंधन',
      'secPest': 'कीट एवं रोग नियंत्रण',
      'secHarvest': 'कटाई एवं भंडारण',
      'secEconomics': 'लागत एवं लाभ',
      'cultivationGuideTitle': 'विस्तृत कृषि मार्गदर्शिका',
      'dosTitle': 'क्या करें?',
      'dontsTitle': 'क्या न करें?',
      'dosDontsHeading': 'किसान सलाह',
      'watchVideo': 'कृषि वीडियो प्रशिक्षण देखें',
      'listenAudio': 'फसल जानकारी सुनें',
      'calcFertilizer': 'इस फसल के लिए खाद की मात्रा निकालें',
      'calcFertilizerSub': 'सटीक NPK एवं सूक्ष्म पोषक तत्व कैलकुलेटर',
      'videoTutorials': 'कृषि वीडियो प्रशिक्षण',
      'viewAll': 'सभी देखें',
      'emergencyTitle': 'किसान आपातकालीन हेल्पलाइन',
      'emergencySubtitle': 'कृषि अधिकारी को निःशुल्क कॉल',
      'tollFree': 'टोल-फ्री 1551',
      'selectLocation': 'अपना क्षेत्र चुनें',
      'photoGalleryTitle': 'फसल फोटो गैलरी',
      'photoGallerySub': 'विवरण देखने के लिए फोटो पर टैप करें',
      'allFilter': 'सभी',
      'kharifFilter': 'खरीफ',
      'rabiFilter': 'रबी',
      'commercialFilter': 'व्यावसायिक',
      'summerFilter': 'ज़ायद / ग्रीष्म',
      'vegetableFilter': 'सब्जियां',
      'speakingVoice': 'सुनाई दे रहा है...',
      'listenVoice': 'सुनें',
      'voiceAiBadge': 'वॉइस AI',
      'voiceAiDesc': 'किसानों के लिए ध्वनि सहायता',
      'views': 'बार देखा गया',
      'schemesTitle': 'सरकारी योजनाएं एवं सब्सिडी',
      'schemesSub': 'सत्यापित राज्य एवं केंद्रीय किसान कल्याण योजनाएं',
      'searchSchemesPlaceholder': 'योजनाएं, सब्सिडी या ऋण खोजें...',
      'telanganaSchemes': 'तेलंगाना योजनाएं',
      'centralSchemes': 'केंद्रीय योजनाएं',
      'allSchemes': 'सभी योजनाएं',
      'subsidyFinder': 'सब्सिडी कैलकुलेटर',
      'myApplications': 'मेरे आवेदन',
      'findSchemesForMe': 'मेरे खेत हेतु योजनाएं',
      'findSchemesForMeSub': 'अपनी भूमि और फसल के आधार पर तत्काल पात्रता जांचें',
      'checkEligibility': 'पात्रता जांचें',
      'verifiedOfficial': 'सत्यापित आधिकारिक स्रोत',
      'viewDetailsApply': 'संपूर्ण विवरण व आवेदन',
      'benefitsTitle': 'मिलने वाले लाभ',
      'eligibilityCriteria': 'पात्रता मापदंड',
      'requiredDocs': 'आवश्यक दस्तावेज',
      'howToApplySteps': 'आवेदन के 5 चरण',
      'applyOnOfficialWebsite': 'आधिकारिक वेबसाइट पर आवेदन करें',
      'deadlineRemaining': 'दिन शेष',
      'helpline': 'हेल्पलाइन',
      'openPortal': 'आधिकारिक पोर्टल खोलें',
      'schemeDisclaimer': 'नोट: सरकारी योजनाओं के नियम बदल सकते हैं। आवेदन से पूर्व आधिकारिक पोर्टल पर नवीनतम जानकारी अवश्य जांचें।',
      'likelyEligible': 'आपके विवरण अनुसार पात्र होने की संभावना',
      'moreInfoRequired': 'सूचीबद्ध नियमों की समीक्षा करें',
      'calculateSubsidy': 'अपनी सब्सिडी की गणना करें',
      'estimatedShare': 'किसान अंशदान',
      'govtSubsidyShare': 'सरकारी सब्सिडी',
      'totalEquipmentCost': 'कुल अनुमानित लागत',
      'statusSubmitted': 'जमा किया गया',
      'statusVerification': 'सत्यापन प्रक्रियाधीन',
      'statusApproved': 'स्वीकृत एवं राशि हस्तांतरित',
      'trackApplication': 'आवेदन स्थिति ट्रैक करें',
      'enterAckNumber': 'आवेदन / पासबुक नंबर दर्ज करें',
      'voiceScreenTitle': 'कृषि मित्र वॉइस AI',
      'voiceScreenSub': 'कोई भी कृषि प्रश्न आवाज़ से पूछें',
      'voiceLanguageNote': 'तेलुगु, हिंदी या अंग्रेज़ी में बोलें',
      'voiceListening': 'सुन रहा हूं... अभी बोलें',
      'voiceSampleTitle': 'नमूना प्रश्न (छूकर पूछें):',
      'voiceMicHint': 'माइक्रोफ़ोन दबाएं या नीचे से नमूना प्रश्न चुनें',
      'voiceQ1': 'मेरे कपास के पत्ते पीले पड़ रहे हैं। क्या करें?',
      'voiceA1': 'कपास में निचली पत्तियां पीली पड़ना नाइट्रोजन या मैग्नीशियम की कमी का संकेत है।\n\nसमाधान:\n1. प्रति एकड़ 25-30 किलो यूरिया डालें।\n2. 2% यूरिया या मैग्नीशियम सल्फेट (10g/लीटर) का छिड़काव करें।',
      'voiceQ2': 'धान में ब्लास्ट रोग के लिए कौन सी दवा लगाएं?',
      'voiceA2': 'धान ब्लास्ट नियंत्रण:\n\n1. ट्राइसाइक्लाज़ोल (0.6g/लीटर) का प्रयोग करें।\n2. नाइट्रोजन खाद कम करें।\n3. ओस सूखने के बाद छिड़काव करें।',
      'voiceQ3': 'आज वारंगल मंडी में कपास का भाव क्या है?',
      'voiceA3': 'आज वारंगल मंडी में कपास:\n\nअधिकतम: ₹7,950 / क्विंटल\nऔसत: ₹7,750 / क्विंटल\nरुझान: कल से +₹150 अधिक।',
      'communityTitle': 'किसान सामुदायिक मंच',
      'communityPostBtn': 'प्रश्न पूछें',
      'communityLikes': 'पसंद',
      'communityReplies': 'जवाब',
      'communityTrending': 'अभी चर्चा में',
      'communityShare': 'अपना अनुभव साझा करें',
      'equipmentTitle': 'ट्रैक्टर & उपकरण किराया',
      'equipmentBook': 'बुक करें',
      'equipmentAvail': 'उपलब्ध',
      'equipmentPerDay': '/दिन',
      'equipmentNearby': 'पास के उपकरण',
      'marketplaceTitle': 'कृषि बाज़ार — ऑनलाइन दुकान',
      'marketplaceCart': 'कार्ट में जोड़ें',
      'marketplaceCertified': 'प्रमाणित',
      'marketplaceSeeds': 'बीज',
      'marketplaceFertilizers': 'खाद',
      'marketplacePesticides': 'कीटनाशक',
      'marketplaceTools': 'कृषि उपकरण',
      'irrTodayNeed': 'आज की जल आवश्यकता',
      'irrWeatherOpt': 'मौसम अनुकूलित',
      'irrLitresDay': 'लीटर / दिन',
      'irrPumpTime': 'पंप चलाने का समय',
      'irrHours': 'घंटे - 5HP ड्रिप',
      'irrRainAdvisory': 'कल बारिश की संभावना है। आज की सिंचाई 50% कम कर सकते हैं।',
      'irrParams': 'खेत के पैरामीटर सेट करें:',
      'irrFarmArea': 'खेत का क्षेत्रफल:',
      'irrAcres': 'एकड़',
      'irrTypeLabel': 'सिंचाई विधि',
      'irrDrip': 'बूंद सिंचाई',
      'irrSprinkler': 'छिड़काव सिंचाई',
      'irrFlood': 'बाढ़ / नाली सिंचाई',
      'irrSoilLabel': 'मिट्टी का प्रकार',
      'soilBlack': 'काली कपास मिट्टी',
      'soilRed': 'लाल दोमट मिट्टी',
      'soilClay': 'चिकनी मिट्टी',
      'irrStageLabel': 'फसल की अवस्था',
      'stageBoll': 'फल / टिंडा विकास',
    }
  };

  static String get(String key, String languageCode) {
    final langMap = localizedValues[languageCode] ?? localizedValues['en']!;
    return langMap[key] ?? localizedValues['en']?[key] ?? key;
  }
}
